version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: apfel
      POSTGRES_PASSWORD: banane
      POSTGRES_DB: schule
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U your_username"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
